### ISSUE TITLE
AMI IDs no longer exist

### ISSUE THREAD

**Issue by dmorand17** [aws-samples/open-on-demand-on-aws#23]
The AMI IDs listed in the [CF template](https://github.com/aws-samples/open-on-demand-on-aws/blob/main/cloudformation/openondemand.yml#L70-L115) are no longer valid and result in the deployment failing due to errors such as

```
You must use a valid fully-formed launch template. The image id '[ami-0ee70e88eed976a1b]' does not exist.
```

cli output checking the us-east-1 AMI id shows no results

```
❯ aws ec2 describe-images \
    --region us-east-1 \
    --image-ids ami-0ee70e88eed976a1b
{
    "Images": []
}
```

**Comment by sean-smith** [comment]
We need to switch this to a parameter based reference, it's just the latest Amazon Linux 2 AMI. You can modify the template to use that.

**Comment by bpeisenbraun** [comment]
That AMI is the Open OnDemand instance, and it's running CentOS Stream 8. I'm not sure why the CentOS project pulled that particular AMI, but you can probably use a similar the current Stream 8 AMI from here: 

https://www.centos.org/download/aws-images/

It would be nice to have the OOD services running on AL2 since the Slurm version mismatch between AL2 and CentOS 8 causes some problems, but I haven't tested that yet.

**Comment by sean-smith** [comment]
Good catch Ben - we should be able to switch to AL2 fairly easily. @cpollard0 thoughts?

**Comment by cpollard0** [comment]
I tried to get it to work with AL2 early on and was unsuccessful so I used CentOS 8. 

I will update the CentOS 8 AMI IDs, then investigate AL2 again with OOD 3.0.

**Comment by cpollard0** [comment]
Merged in a fix this morning; thanks @dmorand17!
